pipeline{
    agent any
    stages{
        stage("Build"){
            steps{
                sh 'cd coit-backend1 && mvn install'
            }
        }
        
        
       stage("Deploy"){
            steps{
                sh 'cd coit-backend1/target/'
                sh 'ls -la'
             
            }
        } 
        
    }
}
