pipeline{
    agent any
    stages{
        stage("Build"){
            steps{
                sh 'cd coit-backend1 && mvn install'
            }
        }
        stage("Setup Env"){
            steps{
                sh 'SA_LOGIC_API_URL http://localhost:5000'
            }
        }
        stage("Deploy"){
            steps{
                sh 'CMD ["java", "-jar", "sentiment-analysis-web-0.0.1.jar", "--sa.logic.api.url=${SA_LOGIC_API_URL}"]'
            }
        }
        
    }
}
