pipeline{
    agent any
    stages{
        stage("Build"){
            steps{
                sh 'cd coit-backend1 && mvn install'
            }
        }
        stage("Deploy"){
            steps{
                sh 'java -jar "sentiment-analysis-web-0.0.1.jar'
            }
        }
        
    }
}
